# Generated by Django 6.0.3 on 2026-04-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
