# Generated by Django 6.0.3 on 2026-04-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('programeers', models.ManyToManyField(to='empDemo.programmer')),
            ],
        ),
    ]
