# Generated by Django 6.0.3 on 2026-04-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('name', models.CharField()),
                ('assignedTo', models.CharField(max_length=40)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
